name: Train and Register Models

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_and_register:
    runs-on: ubuntu-latest
    timeout-minutes: 30 
    strategy:
      matrix:
        model: [logistic_regression, random_forest]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Include comet_ml, scikit-learn, joblib

      # Step 4: Train the model and log to Comet
      - name: Train model and log to Comet
        env:
          COMET_API_KEY: ${{ secrets.COMET_API_KEY }}  # Add your API Key in GitHub secrets
        run: |
          python train.py --model ${{ matrix.model }}

      # Step 5: Register the best model in Comet
      - name: Register best model in Comet
        run: python register_model.py
