name: Train and Register Models

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_logistic_regression:
    runs-on: ubuntu-latest
    env:
      COMET_API_KEY: ${{ secrets.COMET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Logistic Regression
        run: |
          python train.py --model logistic_regression

      - name: Upload logistic_regression_accuracy.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: logistic_regression_accuracy
          path: logistic_regression_accuracy.txt

  train_random_forest:
    runs-on: ubuntu-latest
    env:
      COMET_API_KEY: ${{ secrets.COMET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Random Forest
        run: |
          python train.py --model random_forest

      - name: Upload random_forest_accuracy.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: random_forest_accuracy
          path: random_forest_accuracy.txt

  register_models:
    runs-on: ubuntu-latest
    needs: [train_logistic_regression, train_random_forest] # Ensure this job runs after both training jobs
    env:
      COMET_API_KEY: ${{ secrets.COMET_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Logistic Regression accuracy artifact
        uses: actions/download-artifact@v2
        with:
          name: logistic_regression_accuracy
          path: .

      - name: Download Random Forest accuracy artifact
        uses: actions/download-artifact@v2
        with:
          name: random_forest_accuracy
          path: .

      - name: Register Model
        run: |
          python register_model.py
